version: '3.8'

services:
  app:
    image: mcr.microsoft.com/devcontainers/javascript-node:1-22-bookworm
    volumes:
      - ../:/workspace:cached
    working_dir: /workspace
    ports:
      - "4321:4321"
    command: sh -c "npm install && npm run dev"
